create table if not exists public.umbra_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  occurred_at timestamp with time zone not null default now(),
  session_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  route text not null,
  media_type text,
  provider_id text,
  title_id integer,
  duration_ms integer,
  properties jsonb not null default '{}'::jsonb
);

alter table public.umbra_events enable row level security;

create policy "Only the Umbra admin can view analytics"
on public.umbra_events
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'nishantjha31@gmail.com');
