-- Anime account links and in-app episode notifications.
-- Provider tokens are encrypted by the application before insertion. The
-- encryption key is never stored in Supabase or shipped to the browser.

create table if not exists public.anime_linked_accounts (
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('anilist', 'mal')),
  provider_user_id text not null,
  provider_username text,
  access_token_ciphertext text not null,
  refresh_token_ciphertext text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, provider),
  unique (provider, provider_user_id)
);

alter table public.anime_linked_accounts enable row level security;

create policy "Users can view their anime links"
on public.anime_linked_accounts for select to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their anime links"
on public.anime_linked_accounts for insert to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their anime links"
on public.anime_linked_accounts for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their anime links"
on public.anime_linked_accounts for delete to authenticated
using (auth.uid() = user_id);

create table if not exists public.anime_episode_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anilist_id integer not null check (anilist_id > 0),
  title text not null,
  episode integer not null check (episode > 0),
  aired_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, anilist_id, episode)
);

alter table public.anime_episode_notifications enable row level security;

create policy "Users can view their anime notifications"
on public.anime_episode_notifications for select to authenticated
using (auth.uid() = user_id);

create policy "Users can update their anime notifications"
on public.anime_episode_notifications for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists anime_notifications_user_unread_idx
on public.anime_episode_notifications (user_id, created_at desc)
where read_at is null;

drop trigger if exists set_updated_at_anime_linked_accounts on public.anime_linked_accounts;
create trigger set_updated_at_anime_linked_accounts
before update on public.anime_linked_accounts
for each row execute function public.set_updated_at();
